[build]
  publish = "."

# Permitir acesso direto a recursos estáticos
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat"
  status = 200

# Redirecionar raiz para o manual
[[redirects]]
  from = "/"
  to = "/Manual_Completo_Sistema_Host.html"
  status = 200

# Redirecionar qualquer 404 para o manual principal (apenas para páginas)
[[redirects]]
  from = "/*"
  to = "/Manual_Completo_Sistema_Host.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 